# Generated by Django 4.1.6 on 2023-03-13 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Название")),
                (
                    "slug",
                    models.SlugField(
                        max_length=150, unique=True, verbose_name="URL категории"
                    ),
                ),
                ("order", models.IntegerField(default=1, verbose_name="Порядок меню")),
            ],
            options={
                "verbose_name": "Категорию",
                "verbose_name_plural": "Категории",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Название")),
                ("slug", models.SlugField(unique=True, verbose_name="Url тэга")),
            ],
            options={
                "verbose_name": "Хэштег",
                "verbose_name_plural": "Хэштеги",
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=250, verbose_name="Заголовок"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(
                        upload_to="store/images/", verbose_name="Выбрать фото"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Изменено"),
                ),
                (
                    "on_sale",
                    models.BooleanField(
                        default=False, verbose_name="Показывать на сайте"
                    ),
                ),
                (
                    "views_counter",
                    models.IntegerField(
                        default=0, verbose_name="Количество просмотров"
                    ),
                ),
                ("price", models.IntegerField(default=0, verbose_name="Цена")),
                (
                    "slug",
                    models.SlugField(
                        max_length=150, unique=True, verbose_name="Url для Товара"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        choices=[("n", "new"), ("s", "sale"), ("b", "best")],
                        max_length=1,
                        verbose_name="Бирка",
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        max_length=350,
                        verbose_name="Хэштег для поисковиков",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="store.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="products",
                        to="store.tag",
                        verbose_name="Хэштег",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keywords", models.CharField(max_length=350, verbose_name="Хэштеги")),
                (
                    "image",
                    models.ImageField(
                        upload_to="store/images/", verbose_name="Выбрать фото"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_gallery",
                        to="store.product",
                        verbose_name="Привязка к фото",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фотографию для галереи изображений",
                "verbose_name_plural": "Галерея изображений",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            (None, "---------"),
                            ("m", "Мужчина"),
                            ("f", "Женщина"),
                        ],
                        default="",
                        max_length=1,
                        verbose_name="Пол",
                    ),
                ),
                (
                    "birthday_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Населенный пункт"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Покупателя",
                "verbose_name_plural": "Покупатели",
            },
        ),
    ]
