services:
  mysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    env_file:
      .env
    volumes:
      - mysql_data:/var/lib/mysql/

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/
    env_file:
      - .env
    environment:
        DB_HOST: mysql
    depends_on:
      - mysql

volumes:
  mysql_data:
